# Enable/Disable Built-In Features
aha_board: true
question_board: false

# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
sidebar:
  - 
    label: Discussion
    url: "https://canvas.northwestern.edu/courses/30069/discussion_topics"
    icon: fa-comments
  - 
    label: Grades
    url: "https://canvas.northwestern.edu/courses/30069/gradebook"
    icon: fa-star-o
  -
    label: Syllabus
    url: "https://www.dropbox.com/s/c529lf8rrwg4j0g/KIEI-924-5-71_Winter2016.pdf?preview=KIEI-924-5-71_Winter2016.pdf"
    icon: fa-gavel
    

  
